FROM python:3.10-slim

WORKDIR /app

COPY . .

ARG GIT_COMMIT
ARG BUILD_TIMESTAMP
ENV GIT_COMMIT_HASH=$GIT_COMMIT
ENV BUILD_TIME=$BUILD_TIMESTAMP

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5045
CMD ["python", "-u", "main.py"]
